export enum ERROR_CODES {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  EMAIL_ADDRESS_EXISTS = 'EMAIL_ADDRESS_EXISTS',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
}
